---
name: Firefox
version: 1.0.2
slug: hafirefox
description: Firefox Browser
url: https://github.com/artur-braga/hass-firefox
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - i386
panel_icon: "mdi:firefox"
ingress: true
ingress_port: 5800
ingress_entry: index.html?autoconnect=true
map:
  - config:rw
image: ghcr.io/artur-braga/hass-firefox/hafirefox/{arch}
