---
name: Firefox
version: 1.0.0
slug: hafirefox
description: Firefox Browser
url: https://github.com/artur-braga/hass-firefox
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - i386
panel_icon: "mdi:firefox"
map:
  - config:rw
image: ghcr.io/artur-braga/hass-firefox/hafirefox/{arch}
